# Generated by Django 3.1.3 on 2020-11-14 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 1, 16, 12, 199999)),
        ),
    ]
