# Generated by Django 3.1.3 on 2020-11-15 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0003_auto_20201115_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='division',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Mymensingh', 'Mymensingh'), ('Rangpur', 'Rangpur'), ('Khulna', 'Khulna')], max_length=120),
        ),
        migrations.AlterField(
            model_name='guidedetails',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 18, 38, 47, 958120)),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
