# Generated by Django 3.1.3 on 2020-11-15 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_app', '0004_auto_20201115_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.TimeField(default=datetime.datetime(2020, 11, 15, 18, 57, 21, 372158)),
        ),
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(choices=[('Barguna', 'Barguna'), ('Barisal', 'Barisal'), ('Bhola', 'Bhola'), ('Jhalokati ', 'Jhalokati '), ('Patuakhali ', 'Patuakhali '), ('Pirojpur ', 'Pirojpur '), ('Bandarban ', 'Bandarban '), ('Brahmanbaria ', 'Brahmanbaria '), ('Chandpur ', 'Chandpur '), ('Chittagong ', 'Chittagong '), ('Comilla ', 'Comilla '), ("Cox's Bazar", "Cox's Bazar"), ('Feni ', 'Feni '), ('Khagrachari ', 'Khagrachari '), ('Lakshmipur ', 'Lakshmipur '), ('Noakhali ', 'Noakhali '), ('Rangamati ', 'Rangamati '), ('Dhaka', 'Dhaka'), ('Faridpur ', 'Faridpur '), ('Gazipur ', 'Gazipur '), ('Gopalganj ', 'Gopalganj '), ('Kishoreganj ', 'Kishoreganj '), ('Madaripur ', 'Madaripur '), ('Manikganj ', 'Manikganj '), ('Munshiganj ', 'Munshiganj '), ('Narayanganj ', 'Narayanganj '), ('Narsingdi ', 'Narsingdi '), ('Rajbari ', 'Rajbari '), ('Shariatpur ', 'Shariatpur '), ('Tangail ', 'Tangail '), ('Mymensingh', 'Mymensingh'), ('Jamalpur ', 'Jamalpur '), ('Netrokona ', 'Netrokona '), ('Sherpur ', 'Sherpur '), ('Khulna', 'Khulna'), ('Bagerhat ', 'Bagerhat '), ('Chuadanga ', 'Chuadanga '), ('Jessore ', 'Jessore '), ('Jhenaidah ', 'Jhenaidah '), ('Khulna ', 'Khulna '), ('Kushtia ', 'Kushtia '), ('Magura ', 'Magura '), ('Meherpur ', 'Meherpur '), ('Narail ', 'Narail '), ('Shatkhira ', 'Shatkhira '), ('Rajshahi', 'Rajshahi'), ('Bogra ', 'Bogra '), ('Jaipurhat ', 'Jaipurhat '), ('Naogaon', 'Naogaon'), ('Natore ', 'Natore '), ('Nawabganj ', 'Nawabganj '), ('Pabna ', 'Pabna '), ('Sirajganj ', 'Sirajganj '), ('Rangpur ', 'Rangpur '), ('Gaibandha ', 'Gaibandha '), ('Kurigram ', 'Kurigram '), ('Nilphamari ', 'Nilphamari '), ('Lalmonirhat ', 'Lalmonirhat '), ('Dinajpur ', 'Dinajpur '), ('Thakurgaon ', 'Thakurgaon '), ('Panchagarh ', 'Panchagarh '), ('Sylhet', 'Sylhet'), ('Habiganj ', 'Habiganj '), ('Maulvibazar  ', 'Maulvibazar  '), ('Sunamganj  ', 'Sunamganj  ')], max_length=120),
        ),
    ]
